# Site settings
title: AzizSyed.com
email: aziz.scarn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to AzizSyed.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://azizsyed.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: azizsyed

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed